package com.rumi.buildingmanagement.infrastructure.web.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.UUID;

@Schema(name = "BuildingResponse", description = "A registered building")
public record BuildingResponseDto(
        @Schema(description = "Identifier generated by the service",
                example = "3f2c8a10-5d7b-4e9a-b1c2-0a1b2c3d4e5f")
        UUID id,
        @Schema(description = "Name of the building", example = "Rumi Tower")
        String name,
        @Schema(description = "Street address of the building", example = "Av. Arequipa 1234, Lince, Lima")
        String address
) {
}
