package com.rumi.buildingmanagement.infrastructure.web.dto;

import com.rumi.buildingmanagement.domain.model.InvitationStatus;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.Instant;
import java.util.UUID;

@Schema(name = "InvitationResponse", description = "An invitation for a resident to join a building")
public record InvitationResponseDto(
        @Schema(description = "Identifier generated by the service",
                example = "b7e6d5c4-3a2b-4c1d-9e8f-7a6b5c4d3e2f")
        UUID id,
        @Schema(description = "Identifier of the building the resident is invited to",
                example = "7a9b3c1d-2e4f-4b6a-8c0d-1e2f3a4b5c6d")
        UUID buildingId,
        @Schema(description = "Unique random code the resident enters to join the building",
                example = "RUMI-7K2M9QXD", maxLength = 20)
        String code,
        @Schema(description = "PENDING until the code is used; USED or EXPIRED afterwards", example = "PENDING")
        InvitationStatus status,
        @Schema(description = "Moment the invitation was created (UTC)", example = "2026-10-06T15:30:00Z")
        Instant createdAt
) {
}
