package com.rumi.buildingmanagement.infrastructure.web.dto;

import com.rumi.buildingmanagement.domain.model.SensorStatus;
import com.rumi.buildingmanagement.domain.model.SensorType;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.UUID;

@Schema(name = "SensorResponse", description = "A sensor installed in a building")
public record SensorResponseDto(
        @Schema(description = "Identifier generated by the service",
                example = "5d1c2f0e-8f4a-4a53-9a7e-0f3b1c9d7a11")
        UUID id,
        @Schema(description = "Identifier of the building that owns the sensor",
                example = "7a9b3c1d-2e4f-4b6a-8c0d-1e2f3a4b5c6d")
        UUID buildingId,
        @Schema(description = "Zone of the building where the sensor is installed", example = "FLOOR-3-NORTH")
        String zone,
        @Schema(description = "Kind of sensor", example = "ACCELEROMETER")
        SensorType type,
        @Schema(description = "PENDING when registered, ACTIVE while it reports readings, INACTIVE when disabled",
                example = "PENDING")
        SensorStatus status
) {
}
